import requests
import datetime
import random
import json
import sys
import os

# Configuration
API_URL = os.getenv("API_URL", "http://localhost:8000")
FARMER_ID = "farmer_001"
FIELD_ID = "field_001"

def gen_ts(offset_hours):
    return (datetime.datetime.utcnow() + datetime.timedelta(hours=offset_hours)).isoformat()

def run_simulation():
    global FARMER_ID, FIELD_ID
    print(f"Starting simulation for Field: {FIELD_ID} against {API_URL}")
    
    # 1. Ensure Farmer & Field Exist (using new endpoints)
    print("Creating Farmer...")
    try:
        # Check if exists first or just create and ignore error? simpler to try create or get
        # But for this simple sim, let's just create. ID is autogenerated in model if not provided?
        # Wait, the prompt says "ensure a farmer and a field exist".
        # Our new models use UUID default if not provided, but we want fixed IDs for simulation consistency?
        # The schema definition for FarmerResponse has 'id', create does not enforce it in input.
        # But we can pass 'id' if we want hardcoded ones? Pydantic schema didn't have ID in create.
        # Let's adjust schemas if we want to force ID, OR just use the response ID.
        
        # Actually, let's just create a new one every time? No, that spams DB.
        # Let's try to GET first. But we need ID.
        # Let's assume we want to work with fixed IDs "farmer_001" and "field_001".
        # But standard POST /farmers usually generates ID.
        # Unless we allow passing ID. The model has `id = Column(..., default=generate_uuid)`.
        # If we want to supply ID, we need to add it to Create schema or handle it.
        # Prompt says: "tools/simulate_field.py to use the new POST /farmers and POST /fields".
        # It doesn't strictly say "use specific IDs".
        # So we should Create and capture the ID.
        
        farmer_payload = {"name": "Simulated Farmer", "phone": "1234567890", "language": "en"}
        # But how to prevent duplicates? GET /farmers/{id} needs ID.
        # We can just create new ones. It's a "production-ish MVP".
        
        res = requests.post(f"{API_URL}/farmers", json=farmer_payload)
        if res.status_code == 200:
            farmer_data = res.json()
            FARMER_ID = farmer_data['id']
            print(f"✅ Created/Used Farmer: {FARMER_ID}")
        else:
            print(f"⚠️ Failed to create farmer: {res.text}")
            return

        print("Creating Field...")
        field_payload = {
            "farmer_id": FARMER_ID,
            "name": "Sim Field 1",
            "crop": "wheat",
            "growth_stage": "vegetative",
            "lat": 20.0,
            "lon": 78.0
        }
        res = requests.post(f"{API_URL}/fields", json=field_payload)
        if res.status_code == 200:
            field_data = res.json()
            FIELD_ID = field_data['id']
            print(f"✅ Created/Used Field: {FIELD_ID}")
        else:
            print(f"⚠️ Failed to create field: {res.text}")
            return

    except Exception as e:
        print(f"⚠️ Error in setup: {e}")
        return
        
    # 2. Ingest Sensor Readings (10 over last 24h)
    print("Ingesting sensor readings...")
    for i in range(10):
        # Time spread over last 24h
        offset = -24 + (i * 2.4)
        payload = {
            "field_id": FIELD_ID,
            "ts": gen_ts(offset),
            "moisture": random.uniform(20.0, 40.0), # Randomly wet/dry
            "ph": random.uniform(5.0, 8.0),
            "n": random.uniform(15.0, 60.0),
            "p": random.uniform(10.0, 50.0),
            "k": random.uniform(10.0, 50.0)
        }
        res = requests.post(f"{API_URL}/ingest/sensor", json=payload)
        if res.status_code != 200:
            print(f"Failed to ingest sensor: {res.text}")

    # 3. Ingest Weather Readings (24 hourly over last 24h)
    print("Ingesting past weather...")
    for i in range(24):
        offset = -24 + i
        payload = {
            "field_id": FIELD_ID,
            "ts": gen_ts(offset),
            "temp_c": random.uniform(20.0, 30.0),
            "humidity_pct": random.uniform(40.0, 80.0),
            "rainfall_mm": random.choice([0.0, 0.0, 5.0]) if i > 20 else 0.0 # Some rain recently
        }
        requests.post(f"{API_URL}/ingest/weather", json=payload)

    # 4. Ingest Forecast (12 points for next 72h, every 6h)
    print("Ingesting weather forecast...")
    for i in range(12):
        offset = 1 + (i * 6)
        payload = {
            "field_id": FIELD_ID,
            "ts": gen_ts(offset),
            "temp_c": random.uniform(22.0, 32.0),
            "humidity_pct": random.uniform(30.0, 60.0),
            "rainfall_mm": 0.0 # Dry forecast to trigger irrigation if dry soil
        }
        requests.post(f"{API_URL}/ingest/weather", json=payload)

    # 5. Ingest Images (2 metadata rows)
    print("Ingesting images...")
    img_sources = ["phone", "drone"]
    for i in range(2):
        offset = -2 + i
        payload = {
            "field_id": FIELD_ID,
            "ts": gen_ts(offset),
            "source": img_sources[i],
            "rgb_url": f"http://s3.cloud/bucket/{FIELD_ID}_{i}.jpg",
            "notes": "Healthy crop visible"
        }
        requests.post(f"{API_URL}/ingest/image", json=payload)

    # 6. Call Snapshot
    print(f"Fetching Snapshot for {FIELD_ID}...")
    res = requests.get(f"{API_URL}/field/{FIELD_ID}/latest")
    if res.status_code == 200:
        print("✅ Snapshot retrieved successfully.")
    else:
        print(f"❌ Failed to get snapshot: {res.text}")

    # 7. Call Recommendation
    print(f"Generating Recommendation for {FIELD_ID}...")
    res = requests.post(f"{API_URL}/recommend/{FIELD_ID}")
    if res.status_code == 200:
        print("\n=== RECOMMENDATION ===")
        print(json.dumps(res.json(), indent=2))
        print("======================\n")
    else:
        print(f"❌ Failed to get recommendation: {res.text}")

if __name__ == "__main__":
    run_simulation()
