"""add_sensor_management

Revision ID: 0870afb6d6d4
Revises: f2154cfad47e
Create Date: 2025-12-17 18:19:43.227354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0870afb6d6d4'
down_revision = 'f2154cfad47e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('metrics', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensors_name'), 'sensors', ['name'], unique=False)
    op.create_table('sensor_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sensor_id', sa.String(), nullable=True),
    sa.Column('field_id', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_assignments_field_id'), 'sensor_assignments', ['field_id'], unique=False)
    op.create_index(op.f('ix_sensor_assignments_sensor_id'), 'sensor_assignments', ['sensor_id'], unique=False)
    op.add_column('sensor_readings', sa.Column('sensor_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_sensor_readings_sensor_id'), 'sensor_readings', ['sensor_id'], unique=False)
    op.create_foreign_key(None, 'sensor_readings', 'sensors', ['sensor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sensor_readings', type_='foreignkey')
    op.drop_index(op.f('ix_sensor_readings_sensor_id'), table_name='sensor_readings')
    op.drop_column('sensor_readings', 'sensor_id')
    op.drop_index(op.f('ix_sensor_assignments_sensor_id'), table_name='sensor_assignments')
    op.drop_index(op.f('ix_sensor_assignments_field_id'), table_name='sensor_assignments')
    op.drop_table('sensor_assignments')
    op.drop_index(op.f('ix_sensors_name'), table_name='sensors')
    op.drop_table('sensors')
    # ### end Alembic commands ###
