"""add_feedback

Revision ID: 70db02ac7dd4
Revises: 0001_initial
Create Date: 2025-12-17 13:16:09.906975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70db02ac7dd4'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('field_id', sa.String(), nullable=True),
    sa.Column('recommendation_id', sa.String(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('followed', sa.Boolean(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_field_id'), 'feedback', ['field_id'], unique=False)
    op.create_index(op.f('ix_feedback_recommendation_id'), 'feedback', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_recommendation_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_field_id'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
