"""add_password_reset

Revision ID: 85784f52a7f8
Revises: 0870afb6d6d4
Create Date: 2025-12-17 19:46:50.731525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85784f52a7f8'
down_revision = '0870afb6d6d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmers', sa.Column('reset_code', sa.String(), nullable=True))
    op.add_column('farmers', sa.Column('reset_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farmers', 'reset_expires')
    op.drop_column('farmers', 'reset_code')
    # ### end Alembic commands ###
