"""Add auth fields

Revision ID: f2154cfad47e
Revises: 70db02ac7dd4
Create Date: 2025-12-17 16:11:03.035993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2154cfad47e'
down_revision = '70db02ac7dd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmers', sa.Column('email', sa.String(), nullable=True))
    op.add_column('farmers', sa.Column('password_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_farmers_email'), 'farmers', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farmers_email'), table_name='farmers')
    op.drop_column('farmers', 'password_hash')
    op.drop_column('farmers', 'email')
    # ### end Alembic commands ###
